export const CATEGORY_REQUEST = 'CATEGORY_REQUEST'
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS'
export const CATEGORY_FAIL = 'CATEGORY_FAIL'

export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST'
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL'

export const CHANGE_CAT = 'CHANGE_CAT'


// export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
// export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
// export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

